// <auto-generated />
using System;
using MeetingRoomReservation.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeetingRoomReservation.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260218191423_NormalizeEquipmentStructure")]
    partial class NormalizeEquipmentStructure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MeetingRoomReservation.API.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Projeksiyon"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beyaz Tahta"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Telefon"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ses Sistemi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mikrofon"
                        });
                });

            modelBuilder.Entity("MeetingRoomReservation.API.Entities.RecurringGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RecurringGroups");
                });

            modelBuilder.Entity("MeetingRoomReservation.API.Entities.RecurringGroupExceptionDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ExceptionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecurringGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecurringGroupId");

                    b.ToTable("RecurringGroupExceptionDates");
                });

            modelBuilder.Entity("MeetingRoomReservation.API.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("int");

                    b.Property<int?>("RecurringGroupId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RecurringGroupId");

                    b.HasIndex("RoomId", "StartTime", "EndTime");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("MeetingRoomReservation.API.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 10,
                            CreatedDate = new DateTime(2026, 2, 18, 19, 14, 22, 971, DateTimeKind.Utc).AddTicks(8197),
                            Floor = 1,
                            IsActive = true,
                            Name = "Toplantı Odası A"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 6,
                            CreatedDate = new DateTime(2026, 2, 18, 19, 14, 22, 971, DateTimeKind.Utc).AddTicks(8200),
                            Floor = 2,
                            IsActive = true,
                            Name = "Toplantı Odası B"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 50,
                            CreatedDate = new DateTime(2026, 2, 18, 19, 14, 22, 971, DateTimeKind.Utc).AddTicks(8201),
                            Floor = 3,
                            IsActive = true,
                            Name = "Konferans Salonu"
                        });
                });

            modelBuilder.Entity("RoomEquipments", b =>
                {
                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomEquipments");

                    b.HasData(
                        new
                        {
                            EquipmentId = 1,
                            RoomId = 1
                        },
                        new
                        {
                            EquipmentId = 2,
                            RoomId = 1
                        },
                        new
                        {
                            EquipmentId = 3,
                            RoomId = 1
                        },
                        new
                        {
                            EquipmentId = 1,
                            RoomId = 2
                        },
                        new
                        {
                            EquipmentId = 3,
                            RoomId = 2
                        },
                        new
                        {
                            EquipmentId = 1,
                            RoomId = 3
                        },
                        new
                        {
                            EquipmentId = 2,
                            RoomId = 3
                        },
                        new
                        {
                            EquipmentId = 4,
                            RoomId = 3
                        },
                        new
                        {
                            EquipmentId = 5,
                            RoomId = 3
                        });
                });

            modelBuilder.Entity("MeetingRoomReservation.API.Entities.RecurringGroupExceptionDate", b =>
                {
                    b.HasOne("MeetingRoomReservation.API.Entities.RecurringGroup", "RecurringGroup")
                        .WithMany("ExceptionDates")
                        .HasForeignKey("RecurringGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecurringGroup");
                });

            modelBuilder.Entity("MeetingRoomReservation.API.Entities.Reservation", b =>
                {
                    b.HasOne("MeetingRoomReservation.API.Entities.RecurringGroup", "RecurringGroup")
                        .WithMany("Reservations")
                        .HasForeignKey("RecurringGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MeetingRoomReservation.API.Entities.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecurringGroup");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RoomEquipments", b =>
                {
                    b.HasOne("MeetingRoomReservation.API.Entities.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetingRoomReservation.API.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingRoomReservation.API.Entities.RecurringGroup", b =>
                {
                    b.Navigation("ExceptionDates");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("MeetingRoomReservation.API.Entities.Room", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
